name = "datastructs-fortran"
version = "0.3.6"
license = "LGPL-3.0-or-later"
author = "Wesley Cota"
maintainer = "wlcota@gmail.com"
copyright = "Copyright 2025, Wesley Cota"
description = "A Fortran library for common data structures and random samplers"
keywords = ["fortran", "data structures", "random sampling"]
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = true
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dependencies]
rndgen-fortran.git = "https://github.com/wcota/rndgen-fortran"
stdlib = "*"
